### PR TITLE
Update recruitmentPositions.json

### PR DESCRIPTION
**Pull request by stovatt**
Remove the positions PM for Odin and treasurer.

### CODE REVIEW

**Review by eweilow — APPROVED** [review]
It's the future 🤖

**Comment by stovatt** [comment]
Did I do something wrong since the website didn't change?

**Comment by eweilow** [comment]
You did nothing wrong, our web host just appears to be slow today

**Comment by eweilow** [comment]
It should be published now! You can always verify changes through the deploy preview for future pull requests:
image

In this case the preview for this pull request can be seen on https://deploy-preview-39--aesir.netlify.com/


Generally, the flow for pull requests for this website is:
1. _Automatic:_ Run unit tests on https://travis-ci.org/
2. _Automatic:_ Create a deploy preview (the one above)
3. After merging (which can only be done if steps 1, 2 as well as code review succeeds):
   - _Automatic:_ deploy to https://aesir.se

**Pull request merged**
