### PR TITLE
Remove open positions

### LINKED ISSUE #62: Remove open positions
Since we will open the application now for "Sigmundr" we want everyone to sign up. Easier to remove all the open positions and just have the sign up section at the bottom then to add all the positions haha :)

### PR DESCRIPTION
**Pull request by eweilow**
Closes #62

### CODE REVIEW

**Comment by eweilow** [comment]
@monras accept the invite to the org so I can mark you as needing to accept the change 👍

**Comment by Monras** [comment]
Accepted the invitation now! :D

**Comment by eweilow** [comment]
@Monras You're now added as reviewer, if you approve of the changes at https://deploy-preview-63--aesir.netlify.com/ you can resolve the review 👍

**Review by Monras — CHANGES_REQUESTED** [review]
Great! 
Could we change the text under "Who are we looking for" from: 
"These roles represent some of the roles that we'd like to see you doing at ÆSIR. If you'd like to do something else, you're very welcome to fill in the form below."
To: 
"We are looking for you who have a burning passion for rockets to help build our next rocket!
The roles we are mainly looking for at the moment are the following.
Project positions:
Project managers, Group managers, Team members.
Board positions:
Media responsible, IT responsible, External relations responsible.

If you'd like to do something else, you're very welcome to fill in the form below and let us know! We are allways open for as many people as possible to join our association."

Or something like that? :)

**Comment by eweilow** [comment]
OK, is it better now? 👍

**Review by Monras — APPROVED** [review]

**Review by Monras — APPROVED** [review]

**Review by Monras — APPROVED** [review]

**Comment by Monras** [comment]
Looks good! I approved but still says i need to review? Maybe I just need to wait?

**Comment by eweilow** [comment]
I think there was some weird setting going on haha, but it's good that you approve 3 times 😉

**Comment by Monras** [comment]
Hhaha yea. Who merges the pull request? :)

**Comment by eweilow** [comment]
I just did 👍

**Pull request merged**
